### ISSUE TITLE
last commit says : "add option to disable x-systemd.requires" but option dont shows up

### ISSUE THREAD

**Issue by snow3461** [OpenMediaVault-Plugin-Developers/openmediavault-mergerfsfolders#1]
Hi, 
I see that an checkbox has normally been added to,disable the x-systemd-require options. 
I dont see it, even on a fresh install. Is there a condition for it to show up?

Also, the mnt entry in config.xml doesnt have anything in opts element, thus forbidding us to make any adjustement.

**Comment by ryecoaaron** [comment]
The 5.1.0 package hasn't been released.

There is nothing in opts element in mntent because those are generated from multiple choices in the plugin.  No need to store them in two places.  What are you trying to edit that you can't put in the options box in the plugin?

**Comment by snow3461** [comment]
> 
> 
> The 5.1.0 package hasn't been released.

I see, Is it planned for a release soon ?
> 
> There is nothing in opts element in mntent because those are generated from multiple choices in the plugin. No need to store them in two places. What are you trying to edit that you can't put in the options box in the plugin?

I was basically trying to get rid of those x-systemd-require flag in my fstab, and found no way to do it like i've done before for other mntent entries, nor in the options field of the plugin. It felt weird.

**Comment by ryecoaaron** [comment]
No one was really using the plugin nor asking for the option in it.  So, I guess I was just waiting for other things to add.  But then I just forgot about it.  I will release the package in a bit.

**Comment by snow3461** [comment]
Ok, i guess there are not so much people that needs to fiddle with config to get everything working (i'm using mergerfs on luks volume).

I'm not changing my config too often though, so no worries.

Thank for your work on omv plugins. Really appreciate it.

**Comment by ryecoaaron** [comment]
5.1 is in the repo now.  Let me know if something with the update isn't working.
