### ISSUE TITLE
Wrong fstab is generated when systemd.automount is used

### ISSUE THREAD

**Issue by FujiZ** [OpenMediaVault-Plugin-Developers/openmediavault-mergerfsfolders#2]
When I enabled x-systemd.automount on `/media/disk0` and used it as one of the branches in mergerfs, the fstab file generated by this plugin is wrong; In the options field of the record, I got `defaults,allow_other,use_ino,cache.files=off,category.create=mfs,minfreespace=4G,fsname=storage,x-systemd.requires=/media/disk0 /media/disk0`, which has one extra `/media/disk0`.

I looked into `/srv/salt/omv/deploy/fstab/15mergerfsfolders.sls` and found that this plugin uses `findmnt` to determine the mount point of branch directory, so I ran `findmnt --target /media/disk0` on my machine. Here is the result:

```
TARGET       SOURCE    FSTYPE OPTIONS
/media/disk0 systemd-1 autofs rw,relatime,fd=35,pgrp=1,timeout=0,minproto=5,maxproto=5,direct,pipe_ino=11446
/media/disk0 disk0     9p     rw,noatime,nodiratime,sync,dirsync,access=client,msize=512000,trans=virtio
```

There are 2 records in the result, one is for the original filesystem (`9p` here) and the other is for the systemd.automount. I think that some sort of dedup procedure should be taken to process the result returned by `findmnt`.

**Comment by ryecoaaron** [comment]
While I'm not a fan of blindly taking the first result (maybe pipe to sort and uniq instead?), I can't think of a reason why there would be two different targets given a path.  So, I merged it.
