### ISSUE TITLE
Order of options

### ISSUE THREAD

**Issue by chronic669** [OpenMediaVault-Plugin-Developers/openmediavault-mergerfsfolders#5]
It is currently not possible to change a function policy because any thing you write in options is written in fstab before the category.create policy. As noted in the mergerfs documentation

> NOTE: Options are evaluated in the order listed so if the options are func.rmdir=rand,category.action=ff the action category setting will override the rmdir setting.

should be an easy fix to simply put category.create before any custom options in fstab

**Comment by ryecoaaron** [comment]
Fix in https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-mergerfsfolders/commit/9e73450b8621fdc8f92ad6e9194fb8cbd287e467.  I will try to release a plugin update tomorrow.

**Comment by chronic669** [comment]
That was super fast, is there any way to get the msp policies added thanks

**Comment by ryecoaaron** [comment]
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-mergerfsfolders/commit/03b4adeb73c79d380950ba1bcce4b32958464a33

**Comment by ryecoaaron** [comment]
5.1.3 is in the repo now.

**Comment by chronic669** [comment]
The order is now fixed and I can add func policies, but im still not seeing the newly added policies. Does it require a server restart, if so is there a way to just reload the gui without a full server restart.

**Comment by ryecoaaron** [comment]
ctrl-shift-R in your browser.  If that doesn't work, try apt clean in omv-extras and then ctrl-shift-R.

**Comment by chronic669** [comment]
That worked thanks
